#!/usr/bin/env python3
"""Generate the OAB wordmark lockup as real SVG outlines.

Text in an SVG <text> element renders with whatever font the viewer happens to have,
which makes it useless for a logo. This script converts the wordmark to path data using
the actual Sora glyph outlines, so the result renders identically everywhere.

Requires fontTools and a copy of Sora SemiBold. Both are build-time only; nothing in the
repository depends on them at runtime.

    pip install fonttools
    curl -o Sora-SemiBold.ttf \
      "https://fonts.gstatic.com/s/sora/v17/xMQOuFFYT72X5wkB_18qmnndmSeMmX-K.ttf"
    python3 tools/build_wordmark.py Sora-SemiBold.ttf assets/logo/oab-logo.svg

Sora is licensed under the SIL Open Font License 1.1. Converting glyphs to outlines in a
logo is an ordinary use under that licence; the font file itself is not redistributed here.
"""

import sys

from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.ttLib import TTFont

ACCENT = "#00D1FF"


def glyph_paths(font, text, size, x, y, tracking=0.0):
    """Return (paths, advance) for `text` laid out at `size`, baseline at (x, y).

    Font coordinates are Y-up; SVG is Y-down, so the glyph outline is emitted inside a
    transform that flips Y and scales from units-per-em to the requested size.
    """
    upem = font["head"].unitsPerEm
    scale = size / upem
    cmap = font.getBestCmap()
    glyphs = font.getGlyphSet()
    hmtx = font["hmtx"]

    out = []
    cursor = x
    for ch in text:
        name = cmap.get(ord(ch))
        if name is None:
            raise SystemExit(f"glyph missing from font: {ch!r}")
        advance = hmtx[name][0] * scale
        if ch != " ":
            pen = SVGPathPen(glyphs)
            glyphs[name].draw(pen)
            d = pen.getCommands()
            if d:
                out.append(
                    f'<path transform="translate({cursor:.2f} {y:.2f}) '
                    f'scale({scale:.6f} {-scale:.6f})" d="{d}"/>'
                )
        cursor += advance + tracking
    return out, cursor - x - tracking


def measure(font, text, size, tracking=0.0):
    upem = font["head"].unitsPerEm
    scale = size / upem
    cmap = font.getBestCmap()
    hmtx = font["hmtx"]
    total = sum(hmtx[cmap[ord(c)]][0] * scale + tracking for c in text)
    return total - tracking


def build(font_path, out_path):
    font = TTFont(font_path)

    # --- layout -------------------------------------------------------------
    # Mark occupies a 256-unit square; scale it to 200 tall and place it on the left.
    mark_scale = 200 / 256
    mark_x, mark_y = 4, 20
    # The mark's usable ink is 134 wide inside its 256 box, starting at x=61.
    text_x = mark_x + (61 + 134) * mark_scale + 34

    title_size = 132
    title_track = 1.0
    title_baseline = 130

    sub_size = 27
    sub_track = 5.6
    sub_baseline = 176

    title_paths, title_w = glyph_paths(
        font, "OAB", title_size, text_x, title_baseline, title_track
    )

    # The subtitle is set in three runs so that ARCHITECTURE can carry the accent colour.
    runs = [("OPEN ", "currentColor"), ("ARCHITECTURE ", ACCENT), ("BRAIN", "currentColor")]
    sub_total = measure(font, "".join(r[0] for r in runs), sub_size, sub_track)

    # Optically align the subtitle to the title: match left edges, and if the subtitle is
    # wider than the title the lockup grows to fit it.
    cursor = text_x
    sub_groups = []
    for text, colour in runs:
        paths, _ = glyph_paths(font, text, sub_size, cursor, sub_baseline, sub_track)
        sub_groups.append((colour, paths))
        cursor += measure(font, text, sub_size, sub_track) + sub_track

    width = max(text_x + title_w, text_x + sub_total) + 24
    height = 240

    # --- emit ---------------------------------------------------------------
    mark = f"""  <g transform="translate({mark_x} {mark_y}) scale({mark_scale:.6f})">
    <g fill="none" stroke="currentColor" stroke-width="10" stroke-linejoin="round" stroke-linecap="round">
      <path d="M128 26 L190 44 L128 62 L66 44 Z"/>
      <path d="M128 72 L176.5 100 L176.5 156 L128 184 L79.5 156 L79.5 100 Z"/>
      <path d="M128 128 L79.5 100 M128 128 L176.5 100"/>
      <path d="M128 194 L190 212 L128 230 L66 212 Z"/>
    </g>
    <path d="M128 44 L128 212" fill="none" stroke="{ACCENT}" stroke-width="7"
          stroke-linecap="round" stroke-dasharray="0.5 14"/>
    <g fill="{ACCENT}">
      <path d="M128 37 L139 44 L128 51 L117 44 Z"/>
      <path d="M128 205 L139 212 L128 219 L117 212 Z"/>
    </g>
  </g>"""

    parts = [
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {width:.0f} {height}" '
        f'width="{width:.0f}" height="{height}" role="img" aria-label="OAB — Open Architecture Brain">',
        "  <title>OAB — Open Architecture Brain</title>",
        "  <desc>Generated by tools/build_wordmark.py from Sora SemiBold outlines. Do not hand-edit.</desc>",
        mark,
        '  <g fill="currentColor">',
        *(f"    {p}" for p in title_paths),
        "  </g>",
    ]
    for colour, paths in sub_groups:
        parts.append(f'  <g fill="{colour}">')
        parts.extend(f"    {p}" for p in paths)
        parts.append("  </g>")
    parts.append("</svg>")

    with open(out_path, "w") as fh:
        fh.write("\n".join(parts) + "\n")

    print(f"wrote {out_path}  ({width:.0f}x{height})")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        raise SystemExit(__doc__)
    build(sys.argv[1], sys.argv[2])
