#!/usr/bin/env python3
"""Generate the knowledge indexes that make progressive disclosure work.

An agent cannot read a knowledge base of hundreds of files, and telling it to "consult the
knowledge base" produces either nothing or everything. What works is a cheap per-domain
index it can scan to pick precisely the files a decision depends on.

Generated, never hand-edited:

    knowledge/<domain>/README.md   per-domain index — the progressive-disclosure entry point
    knowledge/INDEX.md             the full map, for humans
    knowledge/index.json           flat records, for programmatic selection

Every index carries applies_at_stage, because that is the field an agent filters on to keep
stage-4 machinery away from a stage-1 system.

    python3 tools/build_index.py            # write the indexes
    python3 tools/build_index.py --check    # fail if they are out of date (CI)
"""

import json
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("missing PyYAML. Install with: pip install -r requirements-dev.txt")

ROOT = Path(__file__).resolve().parent.parent
KNOWLEDGE = ROOT / "knowledge"

BANNER = "<!-- Generated by tools/build_index.py. Do not edit by hand. -->"

DOMAIN_BLURBS = {
    "fundamentals": "The concepts every other domain leans on, including how OAB decides that "
                    "an architecture is proportional to its problem.",
    "databases": "Choosing and operating datastores by workload characteristics rather than "
                 "preference.",
    "caching": "When a cache earns its place, and — more often — when it does not.",
    "messaging": "Asynchronous processing, weighted toward the simple options that are almost "
                 "always sufficient.",
    "reliability": "Failure modes, and the mechanisms that address them with their parameters.",
    "cost": "Infrastructure cost, and the operational cost no cloud calculator models.",
}


def read_units():
    units = []
    for path in sorted(KNOWLEDGE.rglob("*.md")):
        if path.name in ("README.md", "INDEX.md"):
            continue
        text = path.read_text(encoding="utf-8")
        if not text.startswith("---"):
            continue
        parts = text.split("---", 2)
        if len(parts) < 3:
            continue
        try:
            meta = yaml.safe_load(parts[1]) or {}
        except yaml.YAMLError:
            continue
        if not meta.get("id"):
            continue
        meta["_path"] = str(path.relative_to(ROOT))
        meta["_file"] = path.name
        units.append(meta)
    return units


def stages(meta):
    values = meta.get("applies_at_stage") or []
    return ",".join(str(v) for v in values)


def domain_readme(domain, units):
    blurb = DOMAIN_BLURBS.get(domain, "")
    lines = [
        BANNER,
        "",
        f"# {domain.replace('-', ' ').title()}",
        "",
    ]
    if blurb:
        lines += [blurb, ""]
    lines += [
        f"{len(units)} unit(s). `Stages` is the maturity range where a concept applies — an agent "
        "filters on it so that concepts from a larger system than yours are not offered.",
        "",
        "| Concept | Stages | Cost | What it is |",
        "| :-- | :-- | --: | :-- |",
    ]
    for meta in sorted(units, key=lambda m: m["id"]):
        description = " ".join(str(meta.get("description", "")).split())
        lines.append(
            f"| [{meta['title']}]({meta['_file']}) | {stages(meta)} "
            f"| {meta.get('complexity_cost', '')} | {description} |"
        )
    lines += [
        "",
        "`Cost` is the complexity points a concept adds if adopted; 0 means it is a technique "
        "rather than a component. See `frameworks/complexity-budget/`.",
        "",
    ]
    return "\n".join(lines)


def full_index(by_domain):
    total = sum(len(u) for u in by_domain.values())
    lines = [
        BANNER,
        "",
        "# OAB Knowledge Index",
        "",
        (f"{total} unit(s) across {len(by_domain)} domain(s)."
         if total else
         "No knowledge units yet. See "
         "[docs/contributing/knowledge.md](../docs/contributing/knowledge.md) to add the first."),
        "",
        "Each unit is one concept: what it is, when it applies, **when it does not**, its "
        "trade-offs, its failure modes, and how to measure whether it is working.",
        "",
    ]
    for domain in sorted(by_domain):
        units = by_domain[domain]
        lines += [f"## {domain}", ""]
        if DOMAIN_BLURBS.get(domain):
            lines += [DOMAIN_BLURBS[domain], ""]
        for meta in sorted(units, key=lambda m: m["id"]):
            description = " ".join(str(meta.get("description", "")).split())
            lines.append(f"- **[{meta['title']}]({domain}/{meta['_file']})** "
                         f"— {description} *(stages {stages(meta)})*")
        lines.append("")
    return "\n".join(lines)


def json_index(units):
    records = []
    for meta in sorted(units, key=lambda m: m["id"]):
        records.append({
            "id": meta["id"],
            "title": meta["title"],
            "description": " ".join(str(meta.get("description", "")).split()),
            "category": meta.get("category"),
            "path": meta["_path"],
            "applies_at_stage": meta.get("applies_at_stage", []),
            "complexity_cost": meta.get("complexity_cost"),
            "maturity": meta.get("maturity"),
            "confidence": meta.get("confidence"),
            "tags": meta.get("tags", []),
            "related": meta.get("related", []),
            "prerequisites": meta.get("prerequisites", []),
        })
    return json.dumps({"units": records}, indent=2) + "\n"


def build():
    """Return a mapping of path -> desired content."""
    units = read_units()
    by_domain = {}
    for meta in units:
        by_domain.setdefault(meta.get("category", "uncategorised"), []).append(meta)

    outputs = {KNOWLEDGE / domain / "README.md": domain_readme(domain, domain_units)
               for domain, domain_units in by_domain.items()}
    # INDEX.md and index.json are always written, even with no units. knowledge/README.md
    # links to INDEX.md, and a link that only resolves once someone adds content is a
    # broken link on a fresh clone.
    outputs[KNOWLEDGE / "INDEX.md"] = full_index(by_domain)
    outputs[KNOWLEDGE / "index.json"] = json_index(units)
    return outputs


def main(check=False):
    if not KNOWLEDGE.exists():
        print("no knowledge/ yet — nothing to index")
        return 0

    outputs = build()
    stale = []
    for path, content in outputs.items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == content:
            continue
        if check:
            stale.append(path.relative_to(ROOT))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")

    if check:
        if stale:
            print("✗ generated indexes are out of date:\n", file=sys.stderr)
            for path in stale:
                print(f"  {path}", file=sys.stderr)
            print("\n  Run: python3 tools/build_index.py", file=sys.stderr)
            return 1
        print(f"✓ {len(outputs)} generated index file(s) are current")
        return 0

    print(f"✓ wrote {len(outputs)} index file(s)")
    return 0


if __name__ == "__main__":
    sys.exit(main(check="--check" in sys.argv))
